#############################################################################
# Makefile for building: RbfCon
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  RbfCon.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile RbfCon.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O4 -fopenmp -march=native -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -ffast-math -Ofast -O2 -O4 -fopenmp -march=native -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -ffast-math -Ofast -std=c++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O4 -fopenmp -march=native -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -ffast-math -Ofast -O2 -O4 -fopenmp -march=native -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -ffast-math -fopt-info -Ofast -std=c++11 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = RbfCon1.0.0
DISTDIR = /home/sheridan/Desktop/ERGASIES/RbfCon/.tmp/RbfCon1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = CORE/dataset.cpp \
		CORE/parameter.cpp \
		CORE/parameterlist.cpp \
		GE/converter.cc \
		GE/cprogram.cc \
		GE/doublestack.cc \
		GE/fparser.cc \
		GE/integeranneal.cpp \
		GE/neuralparser.cc \
		GE/neuralprogram.cc \
		GE/nncneuralprogram.cc \
		GE/population.cc \
		GE/program.cc \
		GE/rule.cc \
		GE/sigprogram.cc \
		GE/symbol.cc \
		METHODS/adam.cpp \
		METHODS/armadillo1.cpp \
		METHODS/armijosearch.cpp \
		METHODS/bfgs.cpp \
		METHODS/collection.cpp \
		METHODS/differentialevolution.cpp \
		METHODS/doublebox.cpp \
		METHODS/editlogger.cpp \
		METHODS/ego.cpp \
		METHODS/fibonaccisearch.cpp \
		METHODS/filelogger.cpp \
		METHODS/genetic.cpp \
		METHODS/goldensearch.cpp \
		METHODS/gradientdescent.cpp \
		METHODS/gwooptimizer.cpp \
		METHODS/hybridmethod.cpp \
		METHODS/ipso.cpp \
		METHODS/kmeanssampler.cpp \
		METHODS/lbfgs.cpp \
		METHODS/linesearch.cpp \
		METHODS/logger.cpp \
		METHODS/maxwellsampler.cpp \
		METHODS/mean.cpp \
		METHODS/multistart.cpp \
		METHODS/neldermead.cpp \
		METHODS/ofalgorithm.cpp \
		METHODS/optimizer.cpp \
		METHODS/problem.cpp \
		METHODS/problemsampler.cpp \
		METHODS/simanmethod.cpp \
		METHODS/similarity.cpp \
		METHODS/triangularsampler.cpp \
		METHODS/uniformsampler.cpp \
		METHODS/woa.cpp \
		main.cpp 
OBJECTS       = dataset.o \
		parameter.o \
		parameterlist.o \
		converter.o \
		cprogram.o \
		doublestack.o \
		fparser.o \
		integeranneal.o \
		neuralparser.o \
		neuralprogram.o \
		nncneuralprogram.o \
		population.o \
		program.o \
		rule.o \
		sigprogram.o \
		symbol.o \
		adam.o \
		armadillo1.o \
		armijosearch.o \
		bfgs.o \
		collection.o \
		differentialevolution.o \
		doublebox.o \
		editlogger.o \
		ego.o \
		fibonaccisearch.o \
		filelogger.o \
		genetic.o \
		goldensearch.o \
		gradientdescent.o \
		gwooptimizer.o \
		hybridmethod.o \
		ipso.o \
		kmeanssampler.o \
		lbfgs.o \
		linesearch.o \
		logger.o \
		maxwellsampler.o \
		mean.o \
		multistart.o \
		neldermead.o \
		ofalgorithm.o \
		optimizer.o \
		problem.o \
		problemsampler.o \
		simanmethod.o \
		similarity.o \
		triangularsampler.o \
		uniformsampler.o \
		woa.o \
		main.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		RbfCon.pro CORE/dataset.h \
		CORE/parameter.h \
		CORE/parameterlist.h \
		GE/converter.h \
		GE/cprogram.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/integeranneal.h \
		GE/neuralparser.h \
		GE/neuralprogram.h \
		GE/nncneuralprogram.h \
		GE/population.h \
		GE/program.h \
		GE/rule.h \
		GE/sigprogram.h \
		GE/symbol.h \
		METHODS/adam.h \
		METHODS/armadillo1.h \
		METHODS/armijosearch.h \
		METHODS/bfgs.h \
		METHODS/collection.h \
		METHODS/differentialevolution.h \
		METHODS/doublebox.h \
		METHODS/editlogger.h \
		METHODS/ego.h \
		METHODS/fibonaccisearch.h \
		METHODS/filelogger.h \
		METHODS/genetic.h \
		METHODS/goldensearch.h \
		METHODS/gradientdescent.h \
		METHODS/gwooptimizer.h \
		METHODS/hybridmethod.h \
		METHODS/ipso.h \
		METHODS/kmeanssampler.h \
		METHODS/lbfgs.h \
		METHODS/linesearch.h \
		METHODS/logger.h \
		METHODS/maxwellsampler.h \
		METHODS/mean.h \
		METHODS/multistart.h \
		METHODS/neldermead.h \
		METHODS/ofalgorithm.h \
		METHODS/optimizer.h \
		METHODS/problem.h \
		METHODS/problemsampler.h \
		METHODS/simanmethod.h \
		METHODS/similarity.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/woa.h CORE/dataset.cpp \
		CORE/parameter.cpp \
		CORE/parameterlist.cpp \
		GE/converter.cc \
		GE/cprogram.cc \
		GE/doublestack.cc \
		GE/fparser.cc \
		GE/integeranneal.cpp \
		GE/neuralparser.cc \
		GE/neuralprogram.cc \
		GE/nncneuralprogram.cc \
		GE/population.cc \
		GE/program.cc \
		GE/rule.cc \
		GE/sigprogram.cc \
		GE/symbol.cc \
		METHODS/adam.cpp \
		METHODS/armadillo1.cpp \
		METHODS/armijosearch.cpp \
		METHODS/bfgs.cpp \
		METHODS/collection.cpp \
		METHODS/differentialevolution.cpp \
		METHODS/doublebox.cpp \
		METHODS/editlogger.cpp \
		METHODS/ego.cpp \
		METHODS/fibonaccisearch.cpp \
		METHODS/filelogger.cpp \
		METHODS/genetic.cpp \
		METHODS/goldensearch.cpp \
		METHODS/gradientdescent.cpp \
		METHODS/gwooptimizer.cpp \
		METHODS/hybridmethod.cpp \
		METHODS/ipso.cpp \
		METHODS/kmeanssampler.cpp \
		METHODS/lbfgs.cpp \
		METHODS/linesearch.cpp \
		METHODS/logger.cpp \
		METHODS/maxwellsampler.cpp \
		METHODS/mean.cpp \
		METHODS/multistart.cpp \
		METHODS/neldermead.cpp \
		METHODS/ofalgorithm.cpp \
		METHODS/optimizer.cpp \
		METHODS/problem.cpp \
		METHODS/problemsampler.cpp \
		METHODS/simanmethod.cpp \
		METHODS/similarity.cpp \
		METHODS/triangularsampler.cpp \
		METHODS/uniformsampler.cpp \
		METHODS/woa.cpp \
		main.cpp
QMAKE_TARGET  = RbfCon
DESTDIR       = 
TARGET        = RbfCon


first: all
####### Build rules

RbfCon:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RbfCon.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		RbfCon.pro
	$(QMAKE) -o Makefile RbfCon.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
RbfCon.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile RbfCon.pro

qmake_all: FORCE


all: Makefile RbfCon

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CORE/dataset.h CORE/parameter.h CORE/parameterlist.h GE/converter.h GE/cprogram.h GE/doublestack.h GE/fparser.hh GE/integeranneal.h GE/neuralparser.h GE/neuralprogram.h GE/nncneuralprogram.h GE/population.h GE/program.h GE/rule.h GE/sigprogram.h GE/symbol.h METHODS/adam.h METHODS/armadillo1.h METHODS/armijosearch.h METHODS/bfgs.h METHODS/collection.h METHODS/differentialevolution.h METHODS/doublebox.h METHODS/editlogger.h METHODS/ego.h METHODS/fibonaccisearch.h METHODS/filelogger.h METHODS/genetic.h METHODS/goldensearch.h METHODS/gradientdescent.h METHODS/gwooptimizer.h METHODS/hybridmethod.h METHODS/ipso.h METHODS/kmeanssampler.h METHODS/lbfgs.h METHODS/linesearch.h METHODS/logger.h METHODS/maxwellsampler.h METHODS/mean.h METHODS/multistart.h METHODS/neldermead.h METHODS/ofalgorithm.h METHODS/optimizer.h METHODS/problem.h METHODS/problemsampler.h METHODS/simanmethod.h METHODS/similarity.h METHODS/triangularsampler.h METHODS/uniformsampler.h METHODS/woa.h $(DISTDIR)/
	$(COPY_FILE) --parents CORE/dataset.cpp CORE/parameter.cpp CORE/parameterlist.cpp GE/converter.cc GE/cprogram.cc GE/doublestack.cc GE/fparser.cc GE/integeranneal.cpp GE/neuralparser.cc GE/neuralprogram.cc GE/nncneuralprogram.cc GE/population.cc GE/program.cc GE/rule.cc GE/sigprogram.cc GE/symbol.cc METHODS/adam.cpp METHODS/armadillo1.cpp METHODS/armijosearch.cpp METHODS/bfgs.cpp METHODS/collection.cpp METHODS/differentialevolution.cpp METHODS/doublebox.cpp METHODS/editlogger.cpp METHODS/ego.cpp METHODS/fibonaccisearch.cpp METHODS/filelogger.cpp METHODS/genetic.cpp METHODS/goldensearch.cpp METHODS/gradientdescent.cpp METHODS/gwooptimizer.cpp METHODS/hybridmethod.cpp METHODS/ipso.cpp METHODS/kmeanssampler.cpp METHODS/lbfgs.cpp METHODS/linesearch.cpp METHODS/logger.cpp METHODS/maxwellsampler.cpp METHODS/mean.cpp METHODS/multistart.cpp METHODS/neldermead.cpp METHODS/ofalgorithm.cpp METHODS/optimizer.cpp METHODS/problem.cpp METHODS/problemsampler.cpp METHODS/simanmethod.cpp METHODS/similarity.cpp METHODS/triangularsampler.cpp METHODS/uniformsampler.cpp METHODS/woa.cpp main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O4 -fopenmp -march=native -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -ffast-math -Ofast -O2 -O4 -fopenmp -march=native -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -ffast-math -fopt-info -Ofast -std=c++11 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

dataset.o: CORE/dataset.cpp CORE/dataset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataset.o CORE/dataset.cpp

parameter.o: CORE/parameter.cpp CORE/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameter.o CORE/parameter.cpp

parameterlist.o: CORE/parameterlist.cpp CORE/parameterlist.h \
		CORE/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameterlist.o CORE/parameterlist.cpp

converter.o: GE/converter.cc GE/converter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o converter.o GE/converter.cc

cprogram.o: GE/cprogram.cc GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/fparser.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cprogram.o GE/cprogram.cc

doublestack.o: GE/doublestack.cc GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublestack.o GE/doublestack.cc

fparser.o: GE/fparser.cc GE/fparser.hh \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fparser.o GE/fparser.cc

integeranneal.o: GE/integeranneal.cpp GE/integeranneal.h \
		GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integeranneal.o GE/integeranneal.cpp

neuralparser.o: GE/neuralparser.cc GE/neuralparser.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuralparser.o GE/neuralparser.cc

neuralprogram.o: GE/neuralprogram.cc GE/neuralprogram.h \
		GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/sigprogram.h \
		GE/cprogram.h \
		GE/fparser.hh \
		GE/neuralparser.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuralprogram.o GE/neuralprogram.cc

nncneuralprogram.o: GE/nncneuralprogram.cc GE/nncneuralprogram.h \
		GE/neuralprogram.h \
		GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/sigprogram.h \
		GE/cprogram.h \
		GE/fparser.hh \
		GE/neuralparser.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nncneuralprogram.o GE/nncneuralprogram.cc

population.o: GE/population.cc GE/population.h \
		GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/integeranneal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o population.o GE/population.cc

program.o: GE/program.cc GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o program.o GE/program.cc

rule.o: GE/rule.cc GE/rule.h \
		GE/symbol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rule.o GE/rule.cc

sigprogram.o: GE/sigprogram.cc GE/sigprogram.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/fparser.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sigprogram.o GE/sigprogram.cc

symbol.o: GE/symbol.cc GE/symbol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symbol.o GE/symbol.cc

adam.o: METHODS/adam.cpp METHODS/adam.h \
		METHODS/optimizer.h \
		METHODS/problem.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h \
		METHODS/goldensearch.h \
		METHODS/linesearch.h \
		METHODS/fibonaccisearch.h \
		METHODS/armijosearch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adam.o METHODS/adam.cpp

armadillo1.o: METHODS/armadillo1.cpp METHODS/armadillo1.h \
		METHODS/problem.h \
		METHODS/optimizer.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armadillo1.o METHODS/armadillo1.cpp

armijosearch.o: METHODS/armijosearch.cpp METHODS/armijosearch.h \
		METHODS/linesearch.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armijosearch.o METHODS/armijosearch.cpp

bfgs.o: METHODS/bfgs.cpp METHODS/bfgs.h \
		METHODS/optimizer.h \
		METHODS/problem.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bfgs.o METHODS/bfgs.cpp

collection.o: METHODS/collection.cpp METHODS/collection.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o collection.o METHODS/collection.cpp

differentialevolution.o: METHODS/differentialevolution.cpp METHODS/differentialevolution.h \
		METHODS/collection.h \
		METHODS/problem.h \
		METHODS/optimizer.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o differentialevolution.o METHODS/differentialevolution.cpp

doublebox.o: METHODS/doublebox.cpp METHODS/doublebox.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublebox.o METHODS/doublebox.cpp

editlogger.o: METHODS/editlogger.cpp METHODS/editlogger.h \
		METHODS/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editlogger.o METHODS/editlogger.cpp

ego.o: METHODS/ego.cpp METHODS/ego.h \
		METHODS/problem.h \
		METHODS/optimizer.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h \
		METHODS/gradientdescent.h \
		METHODS/linesearch.h \
		METHODS/fibonaccisearch.h \
		METHODS/goldensearch.h \
		METHODS/armijosearch.h \
		METHODS/bfgs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ego.o METHODS/ego.cpp

fibonaccisearch.o: METHODS/fibonaccisearch.cpp METHODS/fibonaccisearch.h \
		METHODS/linesearch.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fibonaccisearch.o METHODS/fibonaccisearch.cpp

filelogger.o: METHODS/filelogger.cpp METHODS/filelogger.h \
		METHODS/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filelogger.o METHODS/filelogger.cpp

genetic.o: METHODS/genetic.cpp METHODS/genetic.h \
		METHODS/collection.h \
		METHODS/problem.h \
		METHODS/optimizer.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o genetic.o METHODS/genetic.cpp

goldensearch.o: METHODS/goldensearch.cpp METHODS/goldensearch.h \
		METHODS/linesearch.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o goldensearch.o METHODS/goldensearch.cpp

gradientdescent.o: METHODS/gradientdescent.cpp METHODS/gradientdescent.h \
		METHODS/optimizer.h \
		METHODS/problem.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h \
		METHODS/linesearch.h \
		METHODS/fibonaccisearch.h \
		METHODS/goldensearch.h \
		METHODS/armijosearch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gradientdescent.o METHODS/gradientdescent.cpp

gwooptimizer.o: METHODS/gwooptimizer.cpp METHODS/gwooptimizer.h \
		METHODS/collection.h \
		METHODS/problem.h \
		METHODS/optimizer.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gwooptimizer.o METHODS/gwooptimizer.cpp

hybridmethod.o: METHODS/hybridmethod.cpp METHODS/hybridmethod.h \
		METHODS/optimizer.h \
		METHODS/problem.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hybridmethod.o METHODS/hybridmethod.cpp

ipso.o: METHODS/ipso.cpp METHODS/ipso.h \
		METHODS/collection.h \
		METHODS/problem.h \
		METHODS/optimizer.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ipso.o METHODS/ipso.cpp

kmeanssampler.o: METHODS/kmeanssampler.cpp METHODS/kmeanssampler.h \
		METHODS/problemsampler.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kmeanssampler.o METHODS/kmeanssampler.cpp

lbfgs.o: METHODS/lbfgs.cpp METHODS/lbfgs.h \
		METHODS/optimizer.h \
		METHODS/problem.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lbfgs.o METHODS/lbfgs.cpp

linesearch.o: METHODS/linesearch.cpp METHODS/linesearch.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linesearch.o METHODS/linesearch.cpp

logger.o: METHODS/logger.cpp METHODS/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o METHODS/logger.cpp

maxwellsampler.o: METHODS/maxwellsampler.cpp METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxwellsampler.o METHODS/maxwellsampler.cpp

mean.o: METHODS/mean.cpp METHODS/mean.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mean.o METHODS/mean.cpp

multistart.o: METHODS/multistart.cpp METHODS/multistart.h \
		METHODS/problem.h \
		METHODS/collection.h \
		METHODS/optimizer.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multistart.o METHODS/multistart.cpp

neldermead.o: METHODS/neldermead.cpp METHODS/neldermead.h \
		METHODS/problem.h \
		METHODS/collection.h \
		METHODS/optimizer.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neldermead.o METHODS/neldermead.cpp

ofalgorithm.o: METHODS/ofalgorithm.cpp METHODS/ofalgorithm.h \
		METHODS/problem.h \
		METHODS/optimizer.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h \
		METHODS/gradientdescent.h \
		METHODS/linesearch.h \
		METHODS/fibonaccisearch.h \
		METHODS/goldensearch.h \
		METHODS/armijosearch.h \
		METHODS/bfgs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ofalgorithm.o METHODS/ofalgorithm.cpp

optimizer.o: METHODS/optimizer.cpp METHODS/optimizer.h \
		METHODS/problem.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h \
		METHODS/gradientdescent.h \
		METHODS/linesearch.h \
		METHODS/fibonaccisearch.h \
		METHODS/goldensearch.h \
		METHODS/armijosearch.h \
		METHODS/bfgs.h \
		METHODS/lbfgs.h \
		METHODS/neldermead.h \
		METHODS/collection.h \
		METHODS/adam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optimizer.o METHODS/optimizer.cpp

problem.o: METHODS/problem.cpp METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o problem.o METHODS/problem.cpp

problemsampler.o: METHODS/problemsampler.cpp METHODS/problemsampler.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o problemsampler.o METHODS/problemsampler.cpp

simanmethod.o: METHODS/simanmethod.cpp METHODS/simanmethod.h \
		METHODS/collection.h \
		METHODS/problem.h \
		METHODS/optimizer.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simanmethod.o METHODS/simanmethod.cpp

similarity.o: METHODS/similarity.cpp METHODS/similarity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o similarity.o METHODS/similarity.cpp

triangularsampler.o: METHODS/triangularsampler.cpp METHODS/triangularsampler.h \
		METHODS/problemsampler.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o triangularsampler.o METHODS/triangularsampler.cpp

uniformsampler.o: METHODS/uniformsampler.cpp METHODS/uniformsampler.h \
		METHODS/problemsampler.h \
		METHODS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uniformsampler.o METHODS/uniformsampler.cpp

woa.o: METHODS/woa.cpp METHODS/woa.h \
		METHODS/optimizer.h \
		METHODS/problem.h \
		CORE/parameter.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		METHODS/maxwellsampler.h \
		METHODS/problemsampler.h \
		METHODS/triangularsampler.h \
		METHODS/uniformsampler.h \
		METHODS/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		CORE/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o woa.o METHODS/woa.cpp

main.o: main.cpp GE/nncneuralprogram.h \
		GE/neuralprogram.h \
		GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/sigprogram.h \
		GE/cprogram.h \
		GE/fparser.hh \
		GE/neuralparser.h \
		METHODS/problem.h \
		GE/population.h \
		GE/converter.h \
		CORE/parameterlist.h \
		CORE/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/RbfCon/bin || mkdir -p $(INSTALL_ROOT)/opt/RbfCon/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/RbfCon/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/RbfCon/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/RbfCon/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/RbfCon/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

